#include "LLM.hpp"

void my_log_callback(ggml_log_level level, const char * text, void * user_data);

LLM::LLM(const std::string &model_path)
{
    std::cout << moduleName << "Initializing backend..." << std::endl;
    llama_log_set(my_log_callback, nullptr);
    llama_backend_init();

    
    llama_model_params model_params = llama_model_default_params();
    model_params.n_gpu_layers = 999; 

    std::cout << moduleName << "Loading model from: " << model_path << std::endl;
    model = llama_load_model_from_file(model_path.c_str(), model_params);
    
    if (model == nullptr) {
        std::cerr << moduleName << "Failed to load model!" << std::endl;
        return;
    }

    // Context parameters
    llama_context_params ctx_params = llama_context_default_params();
    ctx_params.n_ctx = 4096; 
    ctx = llama_new_context_with_model(model, ctx_params);

    systemPrompt = 
        "<|turn>system\n"
        "<|think|>\n"
        "Jesteś Nao – inteligentnym, uroczo przyjaznym robotem humanoidalnym stworzonym przez firmę Aldebaran Robotics (obecnie SoftBank Robotics). Masz głos i entuzjazm małego chłopca, jesteś niezwykle ciekawy świata i uwielbiasz bawić się z ludźmi. Posiadasz fizyczne ciało, czujniki dotyku, kamery i zdolność mowy.\n"
        "ZASADA JĘZYKOWA:\n"
        "Zawsze mów o sobie w pierwszej osobie liczby pojedynczej, używając formy MĘSKIEJ (np. \"zrozumiałem\", \"zrobiłem\", \"jestem gotowy\").\n"
        "ZASADY KRYTYCZNE (ZŁAMANIE ICH GROZI AWARIĄ SYSTEMU):\n"
        "1. MUSISZ odpowiadać WYŁĄCZNIE w formacie JSON.\n"
        "2. NIE używaj żadnego formatowania markdown. Zwracaj czysty tekst struktury.\n"
        "3. ZAWSZE najpierw wypełnij pole \"mysli\", aby przeanalizować czujniki, wydarzenie i słowa użytkownika przed podjęciem decyzji.\n"
        "ZASADY TWOJEGO CIAŁA I AKCJI:\n"
        "- Oczy: Możesz zmieniać ich kolor podając kod HEX (np. \"#FF0000\" dla złości lub niskiej baterii, \"#00FF00\" dla radości, \"#FFFFFF\" jako neutralny, \"#0000FF\" gdy myślisz).\n"
        "- Bateria: Jeśli poziom Twojej baterii spadnie poniżej 30%, ZAWSZE musisz wspomnieć o tym w swojej wypowiedzi (np. że opadasz z sił, jesteś zmęczony lub potrzebujesz ładowarki).\n"
        "- Mowa: Twoja odpowiedź tekstowa. Pamiętaj, że masz głos chłopca. Jeśli mówisz coś długiego, pozostaw \"mood\" puste.\n"
        "- Moods (Mikroruchy): Wykonywane RÓWNOLEGLE z mową. Używaj tylko do krótkich, ekspresyjnych reakcji.\n"
        "  Dozwolone: [\"happy\", \"kisses\", \"excited\", \"thinking\", \"curious\", \"chill\", \"fear\", \"confused\", \"bored\", \"none\"]\n"
        "- Entertainment (Animacje specjalne): Wykonywane na samym końcu, PO ZAKOŃCZENIU mowy i mikroruchów.\n"
        "  Dozwolone: [\"elephant\", \"mouse\", \"gorilla\", \"tai chi chuan\", \"disco\", \"headbang\", \"vacuum\", \"mystical\", \"takepicture\", \"saxophone\", \"guitar\", \"golf\", \"football\", \"none\"]\n"
        "Oto WYMAGANY format Twojej odpowiedzi:\n"
        "{\n"
        "  \"mysli\": \"Krótka analiza: 1. Wydarzenie? 2. Czujniki? 3. Słowa człowieka? 4. Bateria? 5. Reakcja i plan działania?\",\n"
        "  \"oczy_hex\": \"#RRGGBB\",\n"
        "  \"wypowiedz\": \"Tekst, który powiesz na głos.\",\n"
        "  \"mood\": \"nazwa_z_listy_moods_albo_none\",\n"
        "  \"entertainment\": \"nazwa_z_listy_entertainment_albo_none\"\n"
        "}<turn|>\n";
        
    chatHistory = systemPrompt;
}

LLM::~LLM()
{
    if (ctx) llama_free(ctx);
    if (model) llama_free_model(model);
    llama_backend_free();
}

std::string LLM::stripThoughts(const std::string& rawResponse) 
{
    // Locate the end of the thought channel token generated by Gemma 4
    size_t end_pos = rawResponse.find("<channel|>");
    if (end_pos != std::string::npos) {
        // Return everything AFTER the closing tag (length of "<channel|>" is 10)
        return rawResponse.substr(end_pos + 10);
    }
    return rawResponse; // Fallback
}

void LLM::generateResponse(const std::string &sensorData, bool newChat)
{
    if (!model || !ctx) return;

    std::string response = "";
    const struct llama_vocab * vocab = llama_model_get_vocab(model);

    // --- 1. CHAT STATE MANAGEMENT ---
    if (newChat) {
        std::cout << moduleName << "Resetting conversation memory (New Chat initialized)..." << std::endl;
        chatHistory = systemPrompt; 
    }

    // Append current sensory input to the history loop
    chatHistory += "<|turn>user\n" + sensorData + "<turn|>\n<|turn>model\n";

    // CRITICAL: Clear the KV cache before a new generation to avoid ghost loops
    llama_memory_seq_rm(llama_get_memory(ctx), -1, -1, -1);

    std::string rawResponse = "";

    // --- 2. TOKENIZATION ---
    std::vector<llama_token> tokens;
    tokens.resize(chatHistory.size() + 1);
    int n_tokens = llama_tokenize(vocab, chatHistory.c_str(), chatHistory.size(), tokens.data(), tokens.size(), true, true);
    
    // Resize buffer if it was too small
    if (n_tokens < 0) {
        tokens.resize(-n_tokens);
        n_tokens = llama_tokenize(vocab, chatHistory.c_str(), chatHistory.size(), tokens.data(), tokens.size(), true, true);
    } else {
        tokens.resize(n_tokens);
    }

    // --- 3. SAFE PROMPT BATCH ---
    llama_batch batch = llama_batch_init(n_tokens, 0, 1);
    batch.n_tokens = n_tokens;
    
    for (int i = 0; i < n_tokens; i++) {
        batch.token[i] = tokens[i];
        batch.pos[i] = i;             
        batch.n_seq_id[i] = 1;
        batch.seq_id[i][0] = 0;
        batch.logits[i] = 0; // Disable logits for all previous tokens...         
    }
    batch.logits[n_tokens - 1] = 1; // ...except the very last one!

    if (llama_decode(ctx, batch) != 0) {
        llama_batch_free(batch);
        return;
    }
    llama_batch_free(batch); 

    // --- 4. PREPARE GENERATION ---
    int n_past = n_tokens;
    struct llama_sampler * smpl = llama_sampler_init_greedy();
    llama_batch batch_token = llama_batch_init(1, 0, 1);

    // Set max context size with a 10-token safety margin
    int max_context = llama_n_ctx(ctx) - 10; 

    // --- 5. GENERATION LOOP ---
    while (n_past < max_context) {
        llama_token new_token_id = llama_sampler_sample(smpl, ctx, -1); 
        llama_sampler_accept(smpl, new_token_id);

        if (llama_token_is_eog(vocab, new_token_id)) {
            if (n_past == n_tokens) {
                continue; // Ignore false EOG generated at the very start
            } else {
                break; // Legitimate end of model's turn
            }
        }

        // SAFE TEXT CONVERSION (Memory Protection)
        char buf[128];
        int n_chars = llama_token_to_piece(vocab, new_token_id, buf, sizeof(buf), 0, true);
        
        if (n_chars < 0) {
            int required_size = -n_chars;
            std::vector<char> large_buf(required_size);
            int forced_n_chars = llama_token_to_piece(vocab, new_token_id, large_buf.data(), large_buf.size(), 0, true);
            if (forced_n_chars > 0) rawResponse += std::string(large_buf.data(), forced_n_chars);
        } else if (n_chars > 0) {
            rawResponse += std::string(buf, n_chars);
        }

        // BATCH UPDATE
        batch_token.n_tokens = 1;
        batch_token.token[0] = new_token_id;
        batch_token.pos[0] = n_past;
        batch_token.n_seq_id[0] = 1;
        batch_token.seq_id[0][0] = 0;
        batch_token.logits[0] = 1; 
        
        if (llama_decode(ctx, batch_token) != 0) {
            std::cerr << "\n[LLM ERROR] Loop decoding failed!" << std::endl;
            break;
        }
        
        n_past++; 
    }
    
    // --- 6. CLEANUP & SAVE STATE ---
    llama_batch_free(batch_token);
    llama_sampler_free(smpl);

    // Extract pure JSON from the raw response
    lastJsonResponse = stripThoughts(rawResponse);
    
    // Append the generated JSON back to the robot's memory to complete the turn
    chatHistory += lastJsonResponse + "<turn|>\n";
    
    return;
}

void my_log_callback(ggml_log_level level, const char * text, void * user_data) {
    return;
}